name = "UniqueVectors"
uuid = "2fbcfb34-fd0c-5fbb-b5d7-e826d8f5b0a9"
version = "1.1.0"

[compat]
julia = "1.2"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["InteractiveUtils", "Test"]
